apiVersion: v2
name: posts-api
description: Posts API deployment for the infrastructure interview challenge
type: application
version: "0.2.0"
appVersion: "0.2.0"
keywords:
  - posts
  - express
  - typeorm
sources:
  - https://github.com/ArthurSampaio13/infrastructure-interview
maintainers:
  - name: ArthurSampaio13
    url: https://github.com/ArthurSampaio13
